"""Tests for evidence-based playbook derivation."""

from datetime import datetime, timezone, timedelta
from types import SimpleNamespace

from app.services.playbooks import derive_playbook


class FakeQuery:
    def __init__(self, rows, kind):
        self.rows = rows
        self.kind = kind
        self.decision_id = None
        self._brief_id = None

    def join(self, *_args, **_kwargs):
        return self

    def filter(self, *_args, **_kwargs):
        return self

    def order_by(self, *_args, **_kwargs):
        return self

    def filter_by(self, **kwargs):
        self.decision_id = kwargs.get("decision_id")
        self._brief_id = kwargs.get("brief_id")
        return self

    def all(self):
        if self.kind == "flags" and self._brief_id is not None:
            return self.rows.get("flags", {}).get(self._brief_id, [])
        return self.rows.get("decision_outcome_pairs", [])

    def first(self):
        if self.kind == "decision_briefs":
            return self.rows.get("decision_briefs", {}).get(self.decision_id)
        return None


class FakeSession:
    def __init__(self, rows):
        self.rows = rows

    def query(self, *models):
        if len(models) == 2:
            return FakeQuery(self.rows, "decision_outcome")

        model_name = getattr(models[0], "__name__", "")
        if model_name == "DecisionBrief":
            return FakeQuery(self.rows, "decision_briefs")
        if model_name == "Flag":
            return FakeQuery(self.rows, "flags")
        return FakeQuery(self.rows, "other")


def _make_decision(idx: int, *, category: str, result: str, flags: list[str] | None = None):
    decision = SimpleNamespace(
        id=f"dec-{idx}",
        statement=f"Vendor negotiation decision {idx} with payment terms and SLA focus",
        category=category,
        brands=["Brand A", "Brand B"] if idx % 2 == 0 else ["Brand C"],
        status="approved",
        updated_at=datetime(2026, 8, 1, tzinfo=timezone.utc) + timedelta(days=idx),
    )
    outcome = SimpleNamespace(
        decision_id=decision.id,
        result=result,
        metric_deltas={"savings": idx * 1000},
        narrative=f"Outcome narrative {idx}",
        recorded_at=decision.updated_at,
    )
    brief = SimpleNamespace(id=f"brf-{idx}", decision_id=decision.id)
    flag_rows = [SimpleNamespace(severity="high", conflict_text=text) for text in (flags or [])]
    return decision, outcome, brief, flag_rows


def test_derive_playbook_needs_ten_approved_decisions():
    decision_outcome_pairs = []
    decision_briefs = {}
    flags = {}

    for idx in range(10):
        decision, outcome, brief, flag_rows = _make_decision(
            idx,
            category="Vendor Management",
            result="success" if idx < 9 else "failure",
            flags=["New decision contradicts MOQ rule"] if idx == 9 else [],
        )
        decision_outcome_pairs.append((decision, outcome))
        decision_briefs[decision.id] = brief
        flags[brief.id] = flag_rows

    session = FakeSession(
        {
            "decision_outcome_pairs": decision_outcome_pairs,
            "decision_briefs": decision_briefs,
            "flags": flags,
        }
    )

    playbook = derive_playbook(session, "Vendor Management")

    assert playbook is not None
    assert playbook.autoGenerated is True
    assert playbook.evidenceCount == 10
    assert playbook.reviewStatus == "needs_review"
    assert playbook.contradictionCount == 1
    assert "Vendor Negotiation Best Practices" in playbook.title
    assert playbook.sections[0].subsections


def test_derive_playbook_requires_minimum_evidence():
    decision_outcome_pairs = []
    decision_briefs = {}
    flags = {}

    for idx in range(9):
        decision, outcome, brief, flag_rows = _make_decision(
            idx,
            category="Vendor Management",
            result="success",
            flags=[],
        )
        decision_outcome_pairs.append((decision, outcome))
        decision_briefs[decision.id] = brief
        flags[brief.id] = flag_rows

    session = FakeSession(
        {
            "decision_outcome_pairs": decision_outcome_pairs,
            "decision_briefs": decision_briefs,
            "flags": flags,
        }
    )

    assert derive_playbook(session, "Vendor Management") is None
