"""Playbook generation contracts."""

from typing import Literal, Optional

from pydantic import BaseModel, Field


class PlaybookSubSection(BaseModel):
    title: str
    content: str


class PlaybookSection(BaseModel):
    id: str
    title: str
    content: str
    subsections: list[PlaybookSubSection] = Field(default_factory=list)


class DerivedPlaybookResponse(BaseModel):
    id: str
    title: str
    description: str
    category: str
    brands: list[str] = Field(default_factory=list)
    lastUpdated: str
    tags: list[str] = Field(default_factory=list)
    sections: list[PlaybookSection] = Field(default_factory=list)
    autoGenerated: bool = True
    evidenceCount: int = 0
    contradictionCount: int = 0
    reviewStatus: Literal["draft", "needs_review", "approved"] = "draft"
    generatedFromDecisionIds: list[str] = Field(default_factory=list)
    source: Optional[str] = None

